# Generated by Django 3.0.7 on 2022-08-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userepreferences',
            old_name='corrency',
            new_name='currency',
        ),
    ]
